'use client'

import { useEffect, useState } from 'react'
import { animate } from 'animejs'
import { Activity, ArrowUpRight, BarChart3, Beaker, Check, ChevronRight, CircleUserRound, LayoutDashboard, Menu, Palette, PanelLeft, Settings2, ShieldCheck, SlidersHorizontal, Sparkles, X } from 'lucide-react'

type Message = { role: 'user' | 'assistant'; content: string }
type Order = { order_number: string; customer_name: string; project_type: string; quantity_litres: number; status: string; created_at: string }

const starters = ['Help me choose a finish', 'Why is my paint sagging?', 'Design a low-VOC exterior paint']
const nav = [{ id: 'copilot', label: 'Copilot', icon: Sparkles }, { id: 'dashboard', label: 'Dashboard', icon: LayoutDashboard }, { id: 'settings', label: 'Settings', icon: Settings2 }]

export function SmartCoatCopilot() {
  const [view, setView] = useState('copilot')
  const [open, setOpen] = useState(false)
  const [messages, setMessages] = useState<Message[]>([])
  const [input, setInput] = useState('')
  const [loading, setLoading] = useState(false)
  const [orders, setOrders] = useState<Order[]>([])
  const [config, setConfig] = useState({ advisory: true, catalog: true, saveChats: false, model: 'Claude Sonnet 4.6' })

  useEffect(() => { animate('.copilot-orb', { scale: [0.94, 1, 0.94], duration: 2600, ease: 'inOutSine', loop: true }) }, [])
  useEffect(() => { if (view === 'dashboard') fetch('/api/orders').then(r => r.ok ? r.json() : []).then(setOrders).catch(() => setOrders([])) }, [view])

  async function ask(question = input) {
    const content = question.trim(); if (!content || loading) return
    const next = [...messages, { role: 'user' as const, content }]; setMessages(next); setInput(''); setLoading(true)
    try { const response = await fetch('/api/paint-agent', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ messages: next }) }); const data = await response.json(); setMessages([...next, { role: 'assistant', content: data.text ?? data.error ?? 'No answer returned.' }]) } catch { setMessages([...next, { role: 'assistant', content: 'The copilot could not connect. Please try again.' }]) } finally { setLoading(false) }
  }

  return <section className="copilot-app" aria-label="SmartCoat workspace">
    <header className="copilot-topbar"><button className="mobile-menu" type="button" aria-label="Open menu" onClick={() => setOpen(!open)}>{open ? <X size={18} /> : <Menu size={18} />}</button><a className="copilot-brand" href="#top"><span className="brand-mark small-mark">S</span><span>SMARTCOAT <small>WORKSPACE</small></span></a><div className="topbar-actions"><span className="live-state"><i /> AI SYSTEMS ONLINE</span><button className="user-chip" type="button"><CircleUserRound size={16} /> ADMIN</button></div></header>
    <div className="copilot-layout"><aside className={`copilot-sidebar${open ? ' is-open' : ''}`}><div className="workspace-label">WORKSPACE</div>{nav.map(item => <button key={item.id} type="button" className={view === item.id ? 'nav-item active' : 'nav-item'} onClick={() => { setView(item.id); setOpen(false) }}><item.icon size={16} /> {item.label}{item.id === 'copilot' && <span className="nav-live" />}</button>)}<div className="sidebar-bottom"><div className="workspace-card"><span className="copilot-orb"><Beaker size={16} /></span><div><strong>Paint Intelligence</strong><small>Connected to catalog</small></div></div><span className="sidebar-version">SMARTCOAT / V1.0.0</span></div></aside>
      <main className="copilot-main">{view === 'copilot' && <CopilotView messages={messages} input={input} setInput={setInput} loading={loading} ask={ask} />}{view === 'dashboard' && <Dashboard orders={orders} />}{view === 'settings' && <Settings config={config} setConfig={setConfig} />}</main></div>
  </section>
}

function CopilotView({ messages, input, setInput, loading, ask }: { messages: Message[]; input: string; setInput: (v: string) => void; loading: boolean; ask: (q?: string) => void }) { return <div className="copilot-view"><div className="copilot-intro"><div><span className="section-eyebrow">SMARTCOAT AI / COPILOT</span><h1>Your paint<br /><em>co-pilot.</em></h1><p>Practical guidance for colour, formulation, production and quality — in plain language.</p></div><div className="copilot-signal"><Activity size={14} /> READY TO HELP</div></div><div className="copilot-notice"><ShieldCheck size={15} /><span>Advice is a starting point. Check the product sheet and test before making or applying paint.</span></div><div className="copilot-workspace"><div className="copilot-thread" aria-live="polite">{messages.length === 0 ? <div className="copilot-empty"><div className="copilot-hero-icon"><Sparkles size={20} /></div><h2>What are we working on?</h2><p>Ask me anything about your next paint project. I&apos;ll keep the answer useful and easy to follow.</p><div className="copilot-starters">{starters.map(prompt => <button type="button" key={prompt} onClick={() => ask(prompt)}>{prompt}<ArrowUpRight size={14} /></button>)}</div></div> : messages.map((message, index) => <div className={`copilot-message ${message.role}`} key={`${message.role}-${index}`}><span>{message.role === 'user' ? 'YOU' : 'SMARTCOAT COPILOT'}</span><p>{message.content}</p></div>)}{loading && <div className="copilot-message assistant"><span>SMARTCOAT COPILOT</span><p className="typing"><i /><i /><i /> Thinking through the details</p></div>}</div><form className="copilot-composer" onSubmit={event => { event.preventDefault(); ask() }}><input value={input} onChange={e => setInput(e.target.value)} placeholder="Ask about colour, finish, formula or process..." aria-label="Ask SmartCoat Copilot" /><button type="submit" disabled={!input.trim() || loading}><ArrowUpRight size={16} /></button></form></div><div className="copilot-footer"><span><Palette size={14} /> CATALOG CONTEXT ON</span><span><SlidersHorizontal size={14} /> ADVISORY MODE</span><span>SHIFT + ENTER FOR A NEW LINE</span></div></div> }

function Dashboard({ orders }: { orders: Order[] }) { const total = orders.length; const litres = orders.reduce((sum, order) => sum + Number(order.quantity_litres || 0), 0); return <div className="admin-view"><div className="admin-heading"><div><span className="section-eyebrow">ADMIN / OVERVIEW</span><h1>Good morning,<br /><em>team.</em></h1><p>A simple view of what needs your attention.</p></div><button className="admin-action" type="button"><ArrowUpRight size={15} /> EXPORT VIEW</button></div><div className="metric-grid"><Metric label="ORDERS RECEIVED" value={String(total || '—')} detail="All time" icon={BarChart3} /><Metric label="LITRES REQUESTED" value={litres ? litres.toLocaleString() : '—'} detail="Across customer orders" icon={Palette} /><Metric label="COPILOT STATUS" value="ONLINE" detail="Catalog connected" icon={Activity} /></div><div className="admin-table-card"><div className="table-head"><div><span className="section-eyebrow">RECENT ACTIVITY</span><h2>Customer orders</h2></div><span className="table-count">{total} TOTAL</span></div>{orders.length ? <div className="orders-table">{orders.slice(0, 8).map(order => <div className="order-row" key={order.order_number}><strong>{order.order_number}</strong><span>{order.customer_name}</span><span>{order.project_type}</span><span>{order.quantity_litres}L</span><span className="status-pill">{order.status}</span></div>)}</div> : <div className="no-orders"><PackageIcon /><strong>Your order activity will appear here.</strong><span>New customer requests will be easy to review in one place.</span></div>}</div></div> }
function Metric({ label, value, detail, icon: Icon }: { label: string; value: string; detail: string; icon: typeof Activity }) { return <div className="metric-card"><Icon size={16} /><span className="section-eyebrow">{label}</span><strong>{value}</strong><small>{detail}</small></div> }
function PackageIcon() { return <div className="empty-box"><Check size={17} /></div> }
function Settings({ config, setConfig }: { config: { advisory: boolean; catalog: boolean; saveChats: boolean; model: string }; setConfig: (value: { advisory: boolean; catalog: boolean; saveChats: boolean; model: string }) => void }) { const toggle = (key: 'advisory' | 'catalog' | 'saveChats') => setConfig({ ...config, [key]: !config[key] }); return <div className="admin-view settings-view"><div className="admin-heading"><div><span className="section-eyebrow">ADMIN / CONFIGURATION</span><h1>Control the<br /><em>experience.</em></h1><p>Fine-tune how SmartCoat helps your team and customers.</p></div><div className="settings-icon"><Settings2 size={22} /></div></div><div className="settings-grid"><div className="settings-card"><div className="settings-card-head"><SlidersHorizontal size={17} /><div><h2>Copilot behaviour</h2><p>Simple defaults for safer, more useful answers.</p></div></div><SettingRow label="Safety reminders" detail="Show a clear reminder before advice is used" on={config.advisory} onClick={() => toggle('advisory')} /><SettingRow label="Use paint catalogue" detail="Give the copilot access to your live colour range" on={config.catalog} onClick={() => toggle('catalog')} /><SettingRow label="Save conversations" detail="Keep chat history for signed-in admins" on={config.saveChats} onClick={() => toggle('saveChats')} /></div><div className="settings-card"><div className="settings-card-head"><Beaker size={17} /><div><h2>AI model</h2><p>The model used for paint guidance.</p></div></div><label className="model-select">CURRENT MODEL<select value={config.model} onChange={event => setConfig({ ...config, model: event.target.value })}><option>Claude Sonnet 4.6</option><option>GPT-5.2</option><option>Gemini 3 Pro</option></select></label><div className="settings-status"><span className="live-state"><i /> CONNECTED</span><small>Powered by SmartCoat AI Gateway</small></div></div></div><div className="settings-foot"><ShieldCheck size={15} /> Changes apply to new copilot conversations. Production formulas still need professional review.</div></div> }
function SettingRow({ label, detail, on, onClick }: { label: string; detail: string; on: boolean; onClick: () => void }) { return <div className="setting-row"><div><strong>{label}</strong><p>{detail}</p></div><button className={`switch${on ? ' on' : ''}`} type="button" aria-pressed={on} onClick={onClick}><span /></button></div> }
