'use client'

import useSWR from 'swr'
import { useMemo, useState } from 'react'
import { ArrowLeft, ArrowRight, Check, ChevronDown, Minus, Plus, Search, Sparkles, Truck, Warehouse } from 'lucide-react'
import type { PaintColour } from '@/lib/paint-colours'

type CatalogPaint = { id: string; name: string; hex: string; rgb: string; category: string; source_id?: string | null }
const projectTypes = ['House', 'Apartment', 'Office', 'Shop', 'School', 'Hotel', 'Factory', 'Warehouse', 'Commercial Building', 'Other']
const allSurfaces = ['Walls', 'Ceilings', 'Concrete', 'Plaster', 'Metal', 'Wood', 'Masonry', 'Floor', 'Roof']
const stages = ['Colour', 'Paint', 'Project', 'Quantity', 'Details', 'Review']

function Field({ label, required, children }: { label: string; required?: boolean; children: React.ReactNode }) { return <label className="order-field"><span>{label} {required && <em>*</em>}</span>{children}</label> }

export function SmartCoatOrderWorkflow({ selectedColour, onChangeColour }: { selectedColour: PaintColour; onChangeColour: () => void }) {
  const [stage, setStage] = useState(0)
  const [paintId, setPaintId] = useState('')
  const [category, setCategory] = useState('All paints')
  const [search, setSearch] = useState('')
  const [customPaint, setCustomPaint] = useState('')
  const [projectType, setProjectType] = useState('House')
  const [surfaces, setSurfaces] = useState<string[]>(['Walls'])
  const [finish, setFinish] = useState('Exterior')
  const [area, setArea] = useState('')
  const [quantity, setQuantity] = useState(2)
  const [container, setContainer] = useState(20)
  const [delivery, setDelivery] = useState<'delivery' | 'pickup'>('delivery')
  const [submitted, setSubmitted] = useState(false)
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState('')
  const [reference, setReference] = useState('')
  const [details, setDetails] = useState({ name: '', phone: '', email: '', address: '', city: '', state: '', instructions: '' })
  const fetcher = (url: string) => fetch(url).then((response) => response.json())
  const { data: catalog = [], isLoading: catalogLoading } = useSWR<CatalogPaint[]>('/api/paints', fetcher)
  const selectedCatalogPaint = catalog.find((item) => item.id === paintId)
  const paint = selectedCatalogPaint
  const categories = ['All paints', ...Array.from(new Set(catalog.map((item) => item.category).filter(Boolean))), 'Custom paint']
  const filteredPaints = useMemo(() => catalog.filter((item) => (category === 'All paints' || item.category === category) && item.name.toLowerCase().includes(search.toLowerCase())), [catalog, category, search])
  const litres = area ? Math.max(1, Math.ceil(Number(area))) : quantity * container
  const hasPrice = false
  const estimate = null
  const estimatedCoverage = area ? `${area} m² area recorded` : 'Add area to request a quantity estimate'
  const toggleSurface = (surface: string) => setSurfaces((current) => current.includes(surface) ? current.filter((item) => item !== surface) : [...current, surface])
  const go = (next: number) => setStage(Math.max(0, Math.min(5, next)))
  const updateDetail = (key: keyof typeof details, value: string) => setDetails((current) => ({ ...current, [key]: value }))
  const submit = async () => {
    if (!details.name.trim() || !details.phone.trim() || (delivery === 'delivery' && (!details.address.trim() || !details.city.trim() || !details.state.trim()))) return setError('Please complete the required details before submitting.')
    setSaving(true); setError('')
    try {
      const response = await fetch('/api/orders', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ customerName: details.name, phone: details.phone, email: details.email, deliveryAddress: details.address || 'Pickup from Walnus Global', city: details.city || 'Ado-Ekiti', postcode: details.state || 'N/A', projectType, finish, quantityLitres: litres, paintId: paintId === 'custom' ? 'custom' : paintId, customPaint, notes: JSON.stringify({ surfaces, container, delivery, instructions: details.instructions, estimate }) }) })
      const result = await response.json()
      if (!response.ok) throw new Error(result.error)
      setReference(result.orderNumber); setSubmitted(true)
    } catch (submitError) { setError(submitError instanceof Error ? submitError.message : 'We could not save your request.') } finally { setSaving(false) }
  }

  if (submitted) return <section className="order-shell order-confirmation"><div className="confirmation-mark"><Check size={26} /></div><span className="order-eyebrow">QUOTE REQUEST RECEIVED</span><h2>Thank you, {details.name || 'there'}.</h2><p>Your configured estimate is ready. Our team will verify availability, delivery, and the competitor benchmark before confirming.</p><div className="reference-card"><span>REFERENCE</span><strong>{reference}</strong><small>{selectedColour.name} / {paintId === 'custom' ? customPaint || 'Custom paint brief' : paint?.name || 'Paint to be confirmed'} / {litres} L / {estimate !== null ? `₦${estimate.toLocaleString()}` : 'Price on quotation'}</small></div><button className="order-primary" type="button" onClick={() => { setSubmitted(false); go(0) }}>START NEW QUOTE <ArrowRight size={15} /></button></section>

  return <section className="order-shell" id="order"><div className="order-heading"><div><span className="order-eyebrow">SMARTCOAT™ / PAINT ORDER</span><h2>Make it <em>yours.</em></h2><p>A guided quote that compares the market while you configure your project.</p></div><div className="order-index">0{stage + 1}<span>/ 06</span></div></div><nav className="order-progress" aria-label="Order progress">{stages.map((item, index) => <button type="button" key={item} className={index === stage ? 'current' : index < stage ? 'complete' : ''} onClick={() => index <= stage && go(index)}><span>0{index + 1}</span>{item}</button>)}</nav><div className="order-layout"><div className="order-step">
    {stage === 0 && <div className="order-step-content"><div className="step-title"><span>01</span><h3>Choose your colour</h3></div><div className="chosen-colour"><span className="chosen-swatch" style={{ backgroundColor: selectedColour.hex }} /><div><strong>{selectedColour.name}</strong><small>{selectedColour.hex} · {selectedColour.category}</small></div><button type="button" onClick={onChangeColour}>Change colour</button></div><button className="order-primary" type="button" onClick={() => go(1)}>CONTINUE WITH THIS COLOUR <ArrowRight size={15} /></button></div>}
    {stage === 1 && <div className="order-step-content"><div className="step-title"><span>02</span><h3>Choose your paint</h3></div><p className="step-help">Browse every SmartCoat category, search the full paint library, or describe a custom paint brief.</p><div className="category-chips">{categories.map((item) => <button type="button" key={item} className={category === item ? 'selected' : ''} onClick={() => { setCategory(item); if (item === 'Custom paint') setPaintId('custom') }}>{item}</button>)}</div><div className="paint-search"><Search size={15} /><input aria-label="Search paint types" placeholder="Search all paints..." value={search} onChange={(event) => setSearch(event.target.value)} /></div>{category !== 'Custom paint' && <label className="order-field paint-select-field"><span>Paint product {catalogLoading && <small>Loading catalog…</small>}</span><select aria-label="Choose paint product" value={paintId} onChange={(event) => { setPaintId(event.target.value); setContainer(20) }} disabled={catalogLoading || filteredPaints.length === 0}><option value="" disabled>Select a paint</option>{filteredPaints.map((item) => <option value={item.id} key={item.id}>{item.name} · {item.category}</option>)}</select></label>}{category === 'Custom paint' ? <div className="custom-paint-card"><Sparkles size={18} /><Field label="Custom paint brief" required><input value={customPaint} onChange={(event) => setCustomPaint(event.target.value)} placeholder="e.g. anti-mould eggshell for a coastal bedroom" /></Field><small>We&apos;ll match this brief to the closest formulation and benchmark it against the market.</small></div> : <div className="selected-paint-note"><span className="selected-swatch" style={{ backgroundColor: selectedCatalogPaint?.hex ?? '#d8d2c5' }} /><div><strong>{selectedCatalogPaint?.name ?? 'Choose a paint product'}</strong><small>{selectedCatalogPaint?.category ?? 'Use the category filter or search to browse the catalog'}</small></div><span>{catalog.length} paints</span></div>}<button className="order-primary" type="button" disabled={category === 'Custom paint' && !customPaint.trim()} onClick={() => go(2)}>CONTINUE <ArrowRight size={15} /></button></div>}
    {stage === 2 && <div className="order-step-content"><div className="step-title"><span>03</span><h3>Tell us about your project</h3></div><p className="step-help">What are you painting?</p><div className="project-grid">{projectTypes.map((item) => <button type="button" key={item} className={projectType === item ? 'selected' : ''} onClick={() => setProjectType(item)}>{item}</button>)}</div><p className="step-help">Where will it be applied?</p><div className="segmented">{['Interior', 'Exterior', 'Both'].map((item) => <button type="button" key={item} className={finish === item ? 'selected' : ''} onClick={() => setFinish(item)}>{item}</button>)}</div><p className="step-help">Select one or more surfaces.</p><div className="surface-grid">{allSurfaces.map((item) => <button type="button" key={item} className={surfaces.includes(item) ? 'selected' : ''} onClick={() => toggleSurface(item)}>{item}</button>)}</div><button className="order-primary" type="button" onClick={() => go(3)}>CONTINUE <ArrowRight size={15} /></button></div>}
    {stage === 3 && <div className="order-step-content"><div className="step-title"><span>04</span><h3>How much paint do you need?</h3></div><Field label="Approximate area"><div className="input-with-unit"><input type="number" min="0" placeholder="e.g. 120" value={area} onChange={(event) => setArea(event.target.value)} /><span>m²</span></div></Field><button className="text-button" type="button" onClick={() => setArea('')}>I DON&apos;T KNOW THE AREA</button><div className="quantity-row"><div><span className="step-help">Quantity</span><strong>{quantity} <small>drums</small></strong></div><div className="stepper"><button type="button" aria-label="Decrease quantity" onClick={() => setQuantity(Math.max(1, quantity - 1))}><Minus size={15} /></button><span>{quantity}</span><button type="button" aria-label="Increase quantity" onClick={() => setQuantity(quantity + 1)}><Plus size={15} /></button></div></div><div className="container-options"><span className="step-help">Packaging</span><div className="estimate-card"><strong>Packaging options will be confirmed with your quotation.</strong><small>The current catalog record does not expose package sizes, so SmartCoat will not guess.</small></div></div><div className="estimate-card"><span>ESTIMATED COVERAGE</span><strong>{estimatedCoverage}</strong><small>We use typical coverage for a first estimate, then verify the surface with you.</small></div><button className="order-primary" type="button" onClick={() => go(4)}>CONTINUE <ArrowRight size={15} /></button></div>}
    {stage === 4 && <div className="order-step-content"><div className="step-title"><span>05</span><h3>How would you like to receive it?</h3></div><div className="delivery-options"><button type="button" className={delivery === 'delivery' ? 'selected' : ''} onClick={() => setDelivery('delivery')}><Truck size={20} /><strong>Delivery</strong><small>Bring it to your project</small></button><button type="button" className={delivery === 'pickup' ? 'selected' : ''} onClick={() => setDelivery('pickup')}><Warehouse size={20} /><strong>Pick up</strong><small>Collect from Walnus Global</small></button></div>{delivery === 'delivery' ? <div className="detail-grid"><Field label="Delivery address" required><input value={details.address} onChange={(event) => updateDetail('address', event.target.value)} placeholder="Street and number" /></Field><Field label="City" required><input value={details.city} onChange={(event) => updateDetail('city', event.target.value)} /></Field><Field label="State" required><input value={details.state} onChange={(event) => updateDetail('state', event.target.value)} /></Field><Field label="Delivery instructions"><input value={details.instructions} onChange={(event) => updateDetail('instructions', event.target.value)} placeholder="Optional" /></Field></div> : <div className="pickup-note"><Warehouse size={18} /><span>Collection location<br /><strong>Walnus Global Ventures · Ado-Ekiti</strong></span></div>}<button className="order-primary" type="button" onClick={() => go(5)}>CONTINUE <ArrowRight size={15} /></button></div>}
    {stage === 5 && <div className="order-step-content"><div className="step-title"><span>06</span><h3>Your details</h3></div><div className="detail-grid"><Field label="Full name" required><input value={details.name} onChange={(event) => updateDetail('name', event.target.value)} placeholder="Your name" /></Field><Field label="Phone number" required><input type="tel" value={details.phone} onChange={(event) => updateDetail('phone', event.target.value)} placeholder="080..." /></Field><Field label="Email" required><input required type="email" value={details.email} onChange={(event) => updateDetail('email', event.target.value)} placeholder="Optional" /></Field><Field label="Additional instructions"><textarea value={details.instructions} onChange={(event) => updateDetail('instructions', event.target.value)} placeholder="Tell us anything else about your order..." /></Field></div>{error && <p className="order-error" role="alert">{error}</p>}<button className="order-primary" type="button" onClick={submit} disabled={saving}>{saving ? 'SAVING QUOTE...' : <>SUBMIT PAINT ORDER <ArrowRight size={15} /></>}</button></div>}
  </div><aside className="order-summary"><span className="order-eyebrow">LIVE QUOTE</span><div className="summary-colour"><span style={{ backgroundColor: selectedColour.hex }} /><div><strong>{selectedColour.name}</strong><small>{selectedColour.hex}</small></div></div><dl><div><dt>Paint</dt><dd>{paintId === 'custom' ? customPaint || 'Custom brief' : selectedCatalogPaint?.name || 'Choose a paint'}</dd></div><div><dt>Application</dt><dd>{finish} / {surfaces.join(', ')}</dd></div><div><dt>Project</dt><dd>{projectType}</dd></div><div><dt>Quantity</dt><dd>{litres} L</dd></div><div><dt>Receive</dt><dd>{delivery === 'delivery' ? details.city || 'Delivery' : 'Pick up · Ado-Ekiti'}</dd></div></dl><div className="summary-footer"><span>SMARTCOAT QUOTE</span><strong>{hasPrice && estimate !== null ? `₦${estimate.toLocaleString()}` : 'Request quote'}</strong><small>Pricing and packaging will be confirmed from the selected database record.</small></div></aside></div><div className="order-back"><button type="button" onClick={() => go(stage - 1)} disabled={stage === 0}><ArrowLeft size={14} /> BACK</button><span><ChevronDown size={14} /> <strong>Price updates live</strong> as you change paint, area, size, or delivery.</span></div></section>
}

